# No need to set modifyImagesWithDigest to `true` - this is the default
# behavior
signatures:
  - image: "ghcr.io/kubewarden/tests/pod-privileged:v0.2.1"
    certificates:
    - |
      -----BEGIN CERTIFICATE-----
      MIICsjCCAligAwIBAgIUZfoeZRPm91CZevZ1fPbn4+KRd0owCgYIKoZIzj0EAwIw
      gZIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
      bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xIzAhBgNVBAsTGkt1YmV3YXJkZW4g
      SW50ZXJtZWRpYXRlIENBMSMwIQYDVQQDExpLdWJld2FyZGVuIEludGVybWVkaWF0
      ZSBDQTAeFw0yMjExMjkxNjMzMDBaFw0yMzExMjkxNjMzMDBaMIGFMQswCQYDVQQG
      EwJERTEQMA4GA1UECBMHQmF2YXJpYTESMBAGA1UEBxMJTnVyZW1iZXJnMRMwEQYD
      VQQKEwpLdWJld2FyZGVuMRgwFgYDVQQLEw9LdWJld2FyZGVuIFVzZXIxITAfBgNV
      BAMTGHVzZXIxLmN1c3RvbS13aWRnZXRzLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
      AwEHA0IABMcH06eiQcY+sGvNfs+FBxhiv6+4vYIwvCTOVcJTxQpGO2kHo9nkIHGm
      ew6G0ZMsKuyheJvCd1LUJHz+RSyDMmOjgZYwgZMwDgYDVR0PAQH/BAQDAgeAMBMG
      A1UdJQQMMAoGCCsGAQUFBwMDMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFKPNku64
      U0oZNvqknxVxuLawHDoLMB8GA1UdIwQYMBaAFKl15W6Co/ODIBgv1K2RB+xP2CN8
      MB4GA1UdEQQXMBWBE3VzZXIxQGt1YmV3YXJkZW4uaW8wCgYIKoZIzj0EAwIDSAAw
      RQIhANxvHFVCzQ7BBDTzY380U9nGqw5ZMpxsKA676Kihdyk6AiB4AmeNpCW+QSry
      xbm4q79liMgu9eUfkeB8IpstcbXtkg==
      -----END CERTIFICATE-----
    certificateChain:
    - |
      -----BEGIN CERTIFICATE-----
      MIICkzCCAjmgAwIBAgIUYoQFZMd9Ds6sHQ5SyC/Kle/aR6owCgYIKoZIzj0EAwIw
      gYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
      bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xGzAZBgNVBAsTEkt1YmV3YXJkZW4g
      Um9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRlbiBSb290IENBMB4XDTIyMTEyOTE2
      MzMwMFoXDTIzMTEyOTE2MzMwMFowgZIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdC
      YXZhcmlhMRIwEAYDVQQHEwlOdXJlbWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4x
      IzAhBgNVBAsTGkt1YmV3YXJkZW4gSW50ZXJtZWRpYXRlIENBMSMwIQYDVQQDExpL
      dWJld2FyZGVuIEludGVybWVkaWF0ZSBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEH
      A0IABNPgDWYxXyiLYjrOXE/LBxROY7qqSBguesWlJzfMtJdtGAnUsidBLy7Zjflz
      kVePIyZw5ByvkH49gPutPiKL5TejezB5MA4GA1UdDwEB/wQEAwIBBjATBgNVHSUE
      DDAKBggrBgEFBQcDAzASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSpdeVu
      gqPzgyAYL9StkQfsT9gjfDAfBgNVHSMEGDAWgBQ9dmPyMYr8zE/+D6mF0kPQtcB/
      xzAKBggqhkjOPQQDAgNIADBFAiBL/4eG2snFkA97ayzZ2JUQb3C2dZOAFjwbw5Fs
      rel31wIhAPrAk1OYhIN9Q6SD5kHb2vcpen4qRNEiPGAzY7uelJXe
      -----END CERTIFICATE-----
    - |
      -----BEGIN CERTIFICATE-----
      MIICSzCCAfCgAwIBAgIUHKusfkyBA2FHmSje5pEiQAE5L4AwCgYIKoZIzj0EAwIw
      gYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
      bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xGzAZBgNVBAsTEkt1YmV3YXJkZW4g
      Um9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRlbiBSb290IENBMB4XDTIyMTEyOTE2
      MzMwMFoXDTI3MTEyODE2MzMwMFowgYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdC
      YXZhcmlhMRIwEAYDVQQHEwlOdXJlbWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4x
      GzAZBgNVBAsTEkt1YmV3YXJkZW4gUm9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRl
      biBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJvLruo6Lk6thhFGf
      1EoVJblAExTC44nd8Fy2Qmtlu7Gxfc3YCnadvYG+VJGHwV8dW1iRYD/oEoeGIofH
      3KRhXqNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
      BBYEFD12Y/IxivzMT/4PqYXSQ9C1wH/HMAoGCCqGSM49BAMCA0kAMEYCIQCVF8AT
      c9UaPJPbF9lm7ItwQnciJbarLBKi4vPEFFET/gIhANw6VUfxS55hdSCEF27+jvjy
      uDQIMUZKKXu/8si37BkB
      -----END CERTIFICATE-----
    requireRekorBundle: true
